# Generated by Django 5.1.1 on 2024-10-31 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLoadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_id', models.CharField(max_length=100, unique=True)),
                ('topic_id', models.CharField(max_length=100)),
                ('child_order', models.IntegerField()),
                ('spreadsheet_name', models.CharField(max_length=255)),
                ('spreadsheet_id', models.CharField(max_length=100)),
                ('sheet_loading_request_id', models.CharField(max_length=100)),
                ('unlock_request_id', models.CharField(max_length=100)),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('updated_count', models.IntegerField(default=0)),
                ('time_loaded', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('processing_duration', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
