# Generated by Django 5.1.1 on 2024-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceloaddata',
            name='unlock_request_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
