# Generated by Django 5.1.1 on 2024-12-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_resourceloaddata_unlock_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceloaddata',
            name='no_question',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
