# Generated by Django 5.2.4 on 2025-12-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_resourceloaddata_no_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourceloaddata',
            old_name='no_question',
            new_name='no_questions',
        ),
    ]
